name: DXVK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

      steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install System Dependencies
        run: |
          echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          pacman -Syu --noconfirm base-devel sudo mingw-w64-gcc ninja meson

      - name: Create User
        run: |
          useradd -m -G wheel -s /bin/bash user
          echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Compile
        env:
          XDG_CACHE_HOME: /tmp/.cache
        run: |
          chown -R user:user $PWD
          sudo -u user bash -c "
            cd dxvk
            echo $PWD
            export CFLAGS="-flto=auto -O2 -march=nocona -mtune=nocona -mno-avx -mfpmath=sse"
            export CXXFLAGS="-flto=auto -O2 -march=nocona -mtune=nocona -mno-avx -mfpmath=sse"
            export LDFLAGS="-Wl,-O2 -Wl,--sort-common -Wl,--as-needed"
            meson setup build --cross-file "build-win64.txt" --buildtype release --prefix /tmp/binaries --strip -Denable_d3d8=true --wipe
            ninja -C build install
          "

      - name: Archive the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dxvk-build
          path: /tmp/binaries
